import { PrismaClient } from "@prisma/client";
import { notFound } from "next/navigation";

const prisma = new PrismaClient();

export default async function LiveArticlePage({ params }: { params: { slug: string } }) {
  // Find the post in the database using the URL slug
  const post = await prisma.post.findUnique({
    where: { slug: params.slug },
    include: { seo: true }
  });

  // If the URL slug doesn't match anything in the database, show 404
  if (!post) {
    notFound();
  }

  // Safely extract the raw HTML text from the JSON content field generated by TipTap
  const contentObj = post.content as any;
  const htmlContent = contentObj?.text || "";

  return (
    <div className="min-h-screen bg-slate-950 font-sans text-white py-20 px-6">
      <main className="max-w-3xl mx-auto">
        <h1 className="text-4xl md:text-5xl font-bold mb-6 tracking-tight text-slate-100">
          {post.title}
        </h1>
        
        <div className="flex items-center gap-4 mb-10 pb-10 border-b border-slate-800">
          <div className="text-emerald-400 text-sm font-semibold tracking-wide uppercase bg-emerald-500/10 px-3 py-1 rounded-full border border-emerald-500/20">
            DatoChai Exclusive
          </div>
          <div className="text-slate-500 text-sm">
            {new Intl.DateTimeFormat('en-US', { 
              month: 'long', 
              day: 'numeric', 
              year: 'numeric' 
            }).format(post.createdAt)}
          </div>
        </div>

        {/* NEW: Render the Featured Image if the user uploaded one! */}
        {post.featuredImage && (
          <div className="mb-10 w-full rounded-2xl overflow-hidden border border-slate-800 shadow-2xl">
            <img 
              src={post.featuredImage} 
              alt={post.title} 
              className="w-full h-auto object-cover max-h-[500px]" 
            />
          </div>
        )}

        {/* NEW: Safely inject the bold/headings/lists from the TipTap engine */}
        <article 
          className="prose prose-invert prose-emerald prose-lg max-w-none text-slate-300 leading-relaxed"
          dangerouslySetInnerHTML={{ __html: htmlContent }}
        />
      </main>
    </div>
  );
}